"""Independent, deliberately partial ADSP-2100 architectural model."""

from .alu import ALUResult, compute_alu
from .conditions import (
    ConditionInputs,
    DO_TERMINATION_MNEMONICS,
    IF_CONDITION_MNEMONICS,
    evaluate_do_termination,
    evaluate_if_condition,
)
from .dag import DAGResult, compute_dag, original_base_mask, reverse_address
from .mac import MACResult, compute_mac, saturate_mr
from .shifter import ShifterResult, compute_shifter
from .sequencer import (
    ExplicitFlow,
    SequencerFlowResult,
    select_sequencer_flow,
)
from .status import (
    ALUStatusUpdate,
    ASTATBit,
    ASTATState,
    MSTATBit,
    ModeControl,
    StatusCycleInputs,
    StatusCycleResult,
    StatusRegisters,
    apply_status_cycle,
    status_write_conflict,
)
from .registers import (
    ALURegisterWrite,
    ComputationalWriteConflict,
    DREG,
    DREGCycleResult,
    DREGWrite,
    DREGWriteConflict,
    MACRegisterWrite,
    ShifterRegisterWrite,
    apply_computational_cycle,
    apply_dreg_cycle,
    read_dreg,
    validate_dreg_writes,
)
from .model import (
    ADSP2100Model,
    ArchitecturalState,
    ComputationalBank,
    ExactWord,
    MemorySpace,
    MemoryTransaction,
    ReservedOpcode,
    TransactionKind,
    TraceFrame,
    UNKNOWN,
    UnsupportedFeature,
    UnsupportedOpcode,
    mask_to_width,
    sign_extend,
)

__all__ = [
    "ADSP2100Model",
    "ALUResult",
    "ALURegisterWrite",
    "ALUStatusUpdate",
    "ASTATBit",
    "ASTATState",
    "ArchitecturalState",
    "ComputationalBank",
    "ConditionInputs",
    "ComputationalWriteConflict",
    "DO_TERMINATION_MNEMONICS",
    "DAGResult",
    "DREG",
    "DREGCycleResult",
    "DREGWrite",
    "DREGWriteConflict",
    "ExplicitFlow",
    "ExactWord",
    "IF_CONDITION_MNEMONICS",
    "MemorySpace",
    "MemoryTransaction",
    "MSTATBit",
    "ModeControl",
    "MACResult",
    "MACRegisterWrite",
    "ShifterResult",
    "ShifterRegisterWrite",
    "SequencerFlowResult",
    "StatusCycleInputs",
    "StatusCycleResult",
    "StatusRegisters",
    "ReservedOpcode",
    "TransactionKind",
    "TraceFrame",
    "UNKNOWN",
    "UnsupportedFeature",
    "UnsupportedOpcode",
    "evaluate_do_termination",
    "evaluate_if_condition",
    "apply_computational_cycle",
    "apply_dreg_cycle",
    "apply_status_cycle",
    "compute_alu",
    "compute_dag",
    "compute_mac",
    "compute_shifter",
    "mask_to_width",
    "original_base_mask",
    "reverse_address",
    "read_dreg",
    "select_sequencer_flow",
    "sign_extend",
    "saturate_mr",
    "status_write_conflict",
    "validate_dreg_writes",
]
