"""Original ADSP-2100 status/control-register state-transition model.

The model preserves ASTAT's undocumented reset contents per bit and ICNTL's
whole-register reset unknown. MSTAT and IMASK reset to zero. Instruction
decode, SSTAT stack dynamics, and DMD narrow-read extension are deliberately
outside this storage boundary.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import IntEnum

from .model import ExactWord, UNKNOWN, _UnknownValue


class ASTATBit(IntEnum):
    AZ = 0
    AN = 1
    AV = 2
    AC = 3
    AS = 4
    AQ = 5
    MV = 6
    SS = 7


class MSTATBit(IntEnum):
    SECONDARY_REGISTER_BANK = 0
    BIT_REVERSE = 1
    OVERFLOW_LATCH = 2
    AR_SATURATE = 3


class ModeControl(IntEnum):
    NO_CHANGE_ZERO = 0
    NO_CHANGE_ONE = 1
    DEACTIVATE = 2
    ACTIVATE = 3


StatusBit = bool | _UnknownValue
KnownRegister = ExactWord | _UnknownValue


@dataclass(frozen=True)
class ASTATState:
    """Eight independently known or unknown ASTAT bits in bit-number order."""

    bits: tuple[StatusBit, ...] = field(default_factory=lambda: (UNKNOWN,) * 8)

    def __post_init__(self) -> None:
        if len(self.bits) != 8:
            raise ValueError("ASTAT must contain exactly eight bits")
        if any(value is not UNKNOWN and not isinstance(value, bool) for value in self.bits):
            raise TypeError("each ASTAT bit must be bool or UNKNOWN")

    @classmethod
    def from_word(cls, word: ExactWord) -> "ASTATState":
        if word.width != 8:
            raise ValueError("ASTAT move data must be exactly 8 bits")
        return cls(tuple(bool((word.value >> bit) & 1) for bit in range(8)))

    def bit(self, bit: ASTATBit | int) -> StatusBit:
        return self.bits[int(ASTATBit(bit))]

    @property
    def is_fully_known(self) -> bool:
        return all(value is not UNKNOWN for value in self.bits)

    def to_word(self) -> ExactWord:
        if not self.is_fully_known:
            raise ValueError("ASTAT contains one or more unknown bits")
        value = sum(int(bool(bit)) << index for index, bit in enumerate(self.bits))
        return ExactWord(8, value)

    def updated(self, updates: dict[ASTATBit, bool]) -> "ASTATState":
        bits = list(self.bits)
        for bit, value in updates.items():
            bits[int(ASTATBit(bit))] = bool(value)
        return ASTATState(tuple(bits))


@dataclass(frozen=True)
class ALUStatusUpdate:
    """Status generated by one standard, non-division ALU operation."""

    az: bool
    an: bool
    av: bool
    ac: bool
    as_value: bool | None = None


@dataclass(frozen=True)
class StatusStackEntry:
    """ASTAT/MSTAT/IMASK snapshot pushed by interrupt entry."""

    astat: ASTATState
    mstat: ExactWord
    imask: KnownRegister

    def __post_init__(self) -> None:
        if self.mstat.width != 4:
            raise ValueError("stacked MSTAT must be exactly 4 bits")
        if self.imask is not UNKNOWN and (
            not isinstance(self.imask, ExactWord) or self.imask.width != 4
        ):
            raise ValueError("stacked IMASK must be exactly 4 bits or UNKNOWN")

    @classmethod
    def from_word(cls, word: ExactWord) -> "StatusStackEntry":
        if word.width != 16:
            raise ValueError("status-stack word must be exactly 16 bits")
        return cls(
            ASTATState.from_word(ExactWord(8, word.value >> 8)),
            ExactWord(4, (word.value >> 4) & 0xF),
            ExactWord(4, word.value & 0xF),
        )

    def to_word(self) -> ExactWord:
        if not self.astat.is_fully_known or self.imask is UNKNOWN:
            raise ValueError("unknown status-stack entry has no exact word")
        assert isinstance(self.imask, ExactWord)
        return ExactWord(
            16,
            (
                (self.astat.to_word().value << 8)
                | (self.mstat.value << 4)
                | self.imask.value
            ),
        )


@dataclass(frozen=True)
class StatusCycleInputs:
    """Cycle-end writes accepted by the verified status-storage boundary."""

    reset: bool = False
    astat_move: ExactWord | None = None
    mstat_move: ExactWord | None = None
    icntl_move: ExactWord | None = None
    imask_move: ExactWord | None = None
    mode_controls: tuple[ModeControl, ...] = (
        ModeControl.NO_CHANGE_ZERO,
        ModeControl.NO_CHANGE_ZERO,
        ModeControl.NO_CHANGE_ZERO,
        ModeControl.NO_CHANGE_ZERO,
    )
    alu: ALUStatusUpdate | None = None
    divide_aq: bool | None = None
    mac_mv: bool | None = None
    shifter_ss: bool | None = None
    interrupt_entry: int | None = None
    status_restore: StatusStackEntry | None = None

    def __post_init__(self) -> None:
        if self.astat_move is not None and self.astat_move.width != 8:
            raise ValueError("ASTAT move data must be exactly 8 bits")
        if self.mstat_move is not None and self.mstat_move.width != 4:
            raise ValueError("MSTAT move data must be exactly 4 bits")
        if self.icntl_move is not None and self.icntl_move.width != 5:
            raise ValueError("ICNTL move data must be exactly 5 bits")
        if self.imask_move is not None and self.imask_move.width != 4:
            raise ValueError("IMASK move data must be exactly 4 bits")
        if self.interrupt_entry is not None and not 0 <= self.interrupt_entry <= 3:
            raise ValueError("interrupt level must be IRQ0 through IRQ3")
        if len(self.mode_controls) != 4:
            raise ValueError("MSTAT requires exactly four MODE CONTROL fields")
        object.__setattr__(
            self,
            "mode_controls",
            tuple(ModeControl(control) for control in self.mode_controls),
        )


@dataclass(frozen=True)
class StatusRegisters:
    """Implemented status/control state after a documented reset boundary."""

    astat: ASTATState = field(default_factory=ASTATState)
    mstat: ExactWord = field(default_factory=lambda: ExactWord(4, 0))
    icntl: KnownRegister = UNKNOWN
    imask: KnownRegister = field(default_factory=lambda: ExactWord(4, 0))

    def __post_init__(self) -> None:
        if self.mstat.width != 4:
            raise ValueError("MSTAT must be exactly 4 bits")
        if self.icntl is not UNKNOWN and (
            not isinstance(self.icntl, ExactWord) or self.icntl.width != 5
        ):
            raise ValueError("ICNTL must be exactly 5 bits or UNKNOWN")
        if self.imask is not UNKNOWN and (
            not isinstance(self.imask, ExactWord) or self.imask.width != 4
        ):
            raise ValueError("IMASK must be exactly 4 bits or UNKNOWN")

    @classmethod
    def reset(cls) -> "StatusRegisters":
        return cls()

    @property
    def alternate_bank(self) -> bool:
        return bool(self.mstat.value & (1 << MSTATBit.SECONDARY_REGISTER_BANK))

    @property
    def bit_reverse(self) -> bool:
        return bool(self.mstat.value & (1 << MSTATBit.BIT_REVERSE))

    @property
    def overflow_latch(self) -> bool:
        return bool(self.mstat.value & (1 << MSTATBit.OVERFLOW_LATCH))

    @property
    def saturate_ar(self) -> bool:
        return bool(self.mstat.value & (1 << MSTATBit.AR_SATURATE))


@dataclass(frozen=True)
class StatusCycleResult:
    state: StatusRegisters
    write_conflict: bool
    status_push: StatusStackEntry | None = None


def status_write_conflict(inputs: StatusCycleInputs) -> bool:
    """Detect competing writes without defining illegal-instruction priority."""

    if inputs.reset:
        return False
    automatic_astat_sources = sum(
        source is not None
        for source in (
            inputs.alu,
            inputs.divide_aq,
            inputs.mac_mv,
            inputs.shifter_ss,
        )
    )
    active_mode_control = any(
        control in (ModeControl.DEACTIVATE, ModeControl.ACTIVATE)
        for control in inputs.mode_controls
    )
    ordinary_state_write = (
        inputs.astat_move is not None
        or inputs.mstat_move is not None
        or inputs.icntl_move is not None
        or inputs.imask_move is not None
        or automatic_astat_sources != 0
        or active_mode_control
    )
    return (
        automatic_astat_sources > 1
        or (inputs.astat_move is not None and automatic_astat_sources != 0)
        or (inputs.mstat_move is not None and active_mode_control)
        or (
            inputs.status_restore is not None
            and (ordinary_state_write or inputs.interrupt_entry is not None)
        )
    )


def _interrupt_imask(
    icntl: KnownRegister,
    interrupt_level: int,
) -> KnownRegister:
    if icntl is UNKNOWN:
        return UNKNOWN
    if not isinstance(icntl, ExactWord) or icntl.width != 5:
        raise ValueError("ICNTL must be exactly 5 bits or UNKNOWN")
    if not (icntl.value & 0x10):
        return ExactWord(4, 0)
    return ExactWord(4, (0xF << (interrupt_level + 1)) & 0xF)


def apply_status_cycle(
    state: StatusRegisters,
    inputs: StatusCycleInputs,
) -> StatusCycleResult:
    """Apply documented cycle-end status writes.

    Reset invalidates ASTAT and ICNTL while clearing MSTAT and IMASK. A
    recognized interrupt snapshots ASTAT/MSTAT/IMASK and aborts ordinary
    writes before applying the documented interrupt mask. A detected collision
    suppresses every status/control write.
    """

    if inputs.reset:
        return StatusCycleResult(StatusRegisters.reset(), False)
    if status_write_conflict(inputs):
        return StatusCycleResult(state, True)
    if inputs.interrupt_entry is not None:
        pushed = StatusStackEntry(state.astat, state.mstat, state.imask)
        return StatusCycleResult(
            StatusRegisters(
                astat=state.astat,
                mstat=state.mstat,
                icntl=state.icntl,
                imask=_interrupt_imask(state.icntl, inputs.interrupt_entry),
            ),
            False,
            pushed,
        )
    if inputs.status_restore is not None:
        return StatusCycleResult(
            StatusRegisters(
                astat=inputs.status_restore.astat,
                mstat=inputs.status_restore.mstat,
                icntl=state.icntl,
                imask=inputs.status_restore.imask,
            ),
            False,
        )

    astat = state.astat
    if inputs.astat_move is not None:
        astat = ASTATState.from_word(inputs.astat_move)
    elif inputs.alu is not None:
        updates = {
            ASTATBit.AZ: inputs.alu.az,
            ASTATBit.AN: inputs.alu.an,
            ASTATBit.AV: inputs.alu.av,
            ASTATBit.AC: inputs.alu.ac,
        }
        if inputs.alu.as_value is not None:
            updates[ASTATBit.AS] = inputs.alu.as_value
        astat = astat.updated(updates)
    elif inputs.divide_aq is not None:
        astat = astat.updated({ASTATBit.AQ: inputs.divide_aq})
    elif inputs.mac_mv is not None:
        astat = astat.updated({ASTATBit.MV: inputs.mac_mv})
    elif inputs.shifter_ss is not None:
        astat = astat.updated({ASTATBit.SS: inputs.shifter_ss})

    if inputs.mstat_move is not None:
        mstat = inputs.mstat_move
    else:
        mstat_value = state.mstat.value
        for bit, control in enumerate(inputs.mode_controls):
            if control == ModeControl.DEACTIVATE:
                mstat_value &= ~(1 << bit)
            elif control == ModeControl.ACTIVATE:
                mstat_value |= 1 << bit
        mstat = ExactWord(4, mstat_value)

    icntl = state.icntl if inputs.icntl_move is None else inputs.icntl_move
    imask = state.imask if inputs.imask_move is None else inputs.imask_move

    return StatusCycleResult(
        StatusRegisters(
            astat=astat,
            mstat=mstat,
            icntl=icntl,
            imask=imask,
        ),
        False,
    )
