#!/usr/bin/env python3
"""Generate original ADSP-2100 computational DREG SystemVerilog constants."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.generators.validate_register_codes import (  # noqa: E402
    DEFAULT_DATABASE,
    load_and_validate,
)


DEFAULT_OUTPUT = ROOT / "rtl/packages/adsp2100_register_pkg.sv"


def render() -> str:
    data = load_and_validate(DEFAULT_DATABASE)
    computational = data["groups"]["00"]["codes"]
    ordered = sorted(
        ((int(code), metadata["register"]) for code, metadata in computational.items()),
        key=lambda item: item[0],
    )
    lines = [
        "`default_nettype none",
        "",
        "// Generated by tools/generators/generate_register_package.py.",
        "// Values are the original Appendix A computational DREG field.",
        "package adsp2100_register_pkg;",
        "  typedef enum logic [3:0] {",
    ]
    for index, (code, register) in enumerate(ordered):
        comma = "," if index + 1 < len(ordered) else ""
        lines.append(f"    DREG_{register} = 4'h{code:x}{comma}")
    lines.extend(
        [
            "  } dreg_address_t;",
            "endpackage",
            "",
            "`default_nettype wire",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        try:
            existing = args.output.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"FAIL generated file missing: {args.output}", file=sys.stderr)
            return 1
        if existing != rendered:
            print(f"FAIL generated file is stale: {args.output}", file=sys.stderr)
            return 1
        print(f"PASS generated register package is current: {args.output}")
        return 0
    args.output.write_text(rendered, encoding="utf-8")
    print(f"WROTE {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
