#!/usr/bin/env python3
"""Generate reviewed ADSP-2100 instruction-format documentation and RTL constants."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.generators.validate_instruction_formats import (  # noqa: E402
    load_database as load_format_database,
    validate_database as validate_format_database,
)
from tools.generators.validate_isa import (  # noqa: E402
    load_database as load_isa_database,
    validate_database as validate_isa_database,
)


DEFAULT_DOC_OUTPUT = ROOT / "docs/generated/instruction_formats.md"
DEFAULT_RTL_OUTPUT = ROOT / "rtl/packages/adsp2100_format_pkg.sv"


def _field_mask(msb: int, lsb: int) -> int:
    return ((1 << (msb - lsb + 1)) - 1) << lsb


def render_documentation() -> str:
    formats = load_format_database()
    isa = load_isa_database()
    validate_format_database(formats)
    validate_isa_database(isa)
    classes = {
        item["original_type"]: item
        for item in isa["encoding_classes"]
    }
    lines = [
        "# Generated original ADSP-2100 instruction formats",
        "",
        "<!-- Generated by tools/generators/generate_instruction_formats.py; do not hand edit. -->",
        "",
        "This table records bit placement only. It does not claim that every field",
        "combination is legal or that instruction semantics are complete.",
        "",
        "| Type | Class pattern | Fields from high to low | Notes |",
        "|---:|---|---|---|",
    ]
    for record in formats["formats"]:
        original_type = record["original_type"]
        field_labels = []
        for field in record["fields"]:
            if field["msb"] == field["lsb"]:
                bit_range = str(field["msb"])
            else:
                bit_range = f"{field['msb']}:{field['lsb']}"
            field_labels.append(f"`{field['id']}[{bit_range}]`")
        fields = ", ".join(field_labels) if field_labels else "none"
        notes = record["notes"].replace("|", "\\|")
        lines.append(
            f"| {original_type} | "
            f"`{classes[original_type]['encoding_pattern']}` | "
            f"{fields} | {notes} |"
        )
    lines.extend(
        [
            "",
            "Primary source: ADI-UM-1989, printed pp. A-1–A-5 "
            "(scan PDF pp. 140–144).",
            "",
        ]
    )
    return "\n".join(lines)


def render_rtl_package() -> str:
    formats = load_format_database()
    validate_format_database(formats)
    lines = [
        "`default_nettype none",
        "",
        "// Generated by tools/generators/generate_instruction_formats.py.",
        "// These constants describe original Appendix A bit placement only.",
        "package adsp2100_format_pkg;",
        "  import adsp2100_pkg::*;",
        "",
    ]
    for record in formats["formats"]:
        original_type = record["original_type"]
        if not record["fields"]:
            continue
        lines.append(f"  // Original instruction Type {original_type}.")
        for field in record["fields"]:
            prefix = f"TYPE_{original_type:02d}_{field['id']}"
            mask = _field_mask(field["msb"], field["lsb"])
            lines.append(
                f"  localparam program_word_t {prefix}_MASK = "
                f"24'h{mask:06x};"
            )
            lines.append(
                f"  localparam logic [4:0] {prefix}_LSB = "
                f"5'd{field['lsb']};"
            )
        lines.append("")
    lines.extend(
        [
            "endpackage",
            "",
            "`default_nettype wire",
            "",
        ]
    )
    return "\n".join(lines)


def _check_file(path: Path, expected: str) -> bool:
    try:
        actual = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        print(f"FAIL generated file missing: {path}", file=sys.stderr)
        return False
    if actual != expected:
        print(f"FAIL generated file is stale: {path}", file=sys.stderr)
        return False
    print(f"PASS generated file is current: {path}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--doc-output",
        type=Path,
        default=DEFAULT_DOC_OUTPUT,
    )
    parser.add_argument(
        "--rtl-output",
        type=Path,
        default=DEFAULT_RTL_OUTPUT,
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    documentation = render_documentation()
    rtl_package = render_rtl_package()
    if args.check:
        results = (
            _check_file(args.doc_output, documentation),
            _check_file(args.rtl_output, rtl_package),
        )
        return 0 if all(results) else 1

    args.doc_output.write_text(documentation, encoding="utf-8")
    args.rtl_output.write_text(rtl_package, encoding="utf-8")
    print(f"WROTE {args.doc_output}")
    print(f"WROTE {args.rtl_output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
