#!/usr/bin/env python3
"""Generate synthesizable original ADSP-2100 class decode from ISA masks."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.generators.validate_isa import DEFAULT_DATABASE, load_database, validate_database


DEFAULT_OUTPUT = ROOT / "rtl/packages/adsp2100_decode_pkg.sv"


def render() -> str:
    data = load_database(DEFAULT_DATABASE)
    validate_database(data)
    lines = [
        "`default_nettype none",
        "",
        "// Generated by tools/generators/generate_decode_package.py.",
        "// The enum identifies original Appendix A classes; it does not imply",
        "// that the semantic instruction within a class is implemented.",
        "package adsp2100_decode_pkg;",
        "  import adsp2100_pkg::*;",
        "",
        "  typedef enum logic [4:0] {",
        "    INSTRUCTION_RESERVED_UNSHOWN = 5'd0,",
    ]
    for index, encoding_class in enumerate(data["encoding_classes"]):
        comma = "," if index + 1 < len(data["encoding_classes"]) else ""
        lines.append(
            f"    INSTRUCTION_TYPE_{encoding_class['original_type']:02d} = "
            f"5'd{encoding_class['original_type']}{comma}"
        )
    lines.extend(
        [
            "  } instruction_class_t;",
            "",
            "  function automatic instruction_class_t decode_instruction_class(",
            "    input program_word_t opcode",
            "  );",
        ]
    )
    for index, encoding_class in enumerate(data["encoding_classes"]):
        keyword = "if" if index == 0 else "else if"
        lines.append(
            f"    {keyword} ((opcode & 24'h{int(encoding_class['opcode_mask'], 16):06x}) "
            f"== 24'h{int(encoding_class['opcode_value'], 16):06x}) begin"
        )
        lines.append(
            "      return "
            f"INSTRUCTION_TYPE_{encoding_class['original_type']:02d};"
        )
        lines.append("    end")
    lines.extend(
        [
            "    else begin",
            "      return INSTRUCTION_RESERVED_UNSHOWN;",
            "    end",
            "  endfunction",
            "endpackage",
            "",
            "`default_nettype wire",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        try:
            existing = args.output.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"FAIL generated file missing: {args.output}", file=sys.stderr)
            return 1
        if existing != rendered:
            print(f"FAIL generated file is stale: {args.output}", file=sys.stderr)
            return 1
        print(f"PASS generated decode package is current: {args.output}")
        return 0
    args.output.write_text(rendered, encoding="utf-8")
    print(f"WROTE {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
