#!/usr/bin/env python3
"""Render the reviewed original opcode-class table from the ISA database."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.generators.validate_isa import DEFAULT_DATABASE, load_database, validate_database


DEFAULT_OUTPUT = ROOT / "docs/generated/opcode_classes.md"


def render() -> str:
    data = load_database(DEFAULT_DATABASE)
    validate_database(data)
    lines = [
        "# Generated original ADSP-2100 opcode classes",
        "",
        "<!-- Generated by tools/generators/generate_opcode_table.py; do not hand edit. -->",
        "",
        "| Type | Name | 24-bit pattern | Mask | Value | Confidence |",
        "|---:|---|---|---:|---:|---|",
    ]
    shown = 0
    for encoding_class in data["encoding_classes"]:
        mask = int(encoding_class["opcode_mask"], 16)
        shown += 1 << (24 - mask.bit_count())
        lines.append(
            f"| {encoding_class['original_type']} | {encoding_class['name']} | "
            f"`{encoding_class['encoding_pattern']}` | "
            f"`{encoding_class['opcode_mask']}` | "
            f"`{encoding_class['opcode_value']}` | "
            f"{encoding_class['confidence']} |"
        )
    lines.extend(
        [
            "",
            f"The explicit, non-overlapping classes cover {shown:,} of "
            f"{1 << 24:,} 24-bit words. The remaining {(1 << 24) - shown:,} "
            "words are `RESERVED_UNSHOWN`; their execution behavior is undocumented "
            "and must fail closed.",
            "",
            "Source locations are retained per class in "
            "`docs/generated/adsp2100_isa.yaml`.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        try:
            existing = args.output.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"FAIL generated file missing: {args.output}", file=sys.stderr)
            return 1
        if existing != rendered:
            print(f"FAIL generated file is stale: {args.output}", file=sys.stderr)
            return 1
        print(f"PASS generated opcode table is current: {args.output}")
        return 0
    args.output.write_text(rendered, encoding="utf-8")
    print(f"WROTE {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
