`default_nettype none

// Generated by tools/generators/generate_decode_package.py.
// The enum identifies original Appendix A classes; it does not imply
// that the semantic instruction within a class is implemented.
package adsp2100_decode_pkg;
  import adsp2100_pkg::*;

  typedef enum logic [4:0] {
    INSTRUCTION_RESERVED_UNSHOWN = 5'd0,
    INSTRUCTION_TYPE_01 = 5'd1,
    INSTRUCTION_TYPE_02 = 5'd2,
    INSTRUCTION_TYPE_03 = 5'd3,
    INSTRUCTION_TYPE_04 = 5'd4,
    INSTRUCTION_TYPE_05 = 5'd5,
    INSTRUCTION_TYPE_06 = 5'd6,
    INSTRUCTION_TYPE_07 = 5'd7,
    INSTRUCTION_TYPE_08 = 5'd8,
    INSTRUCTION_TYPE_09 = 5'd9,
    INSTRUCTION_TYPE_10 = 5'd10,
    INSTRUCTION_TYPE_11 = 5'd11,
    INSTRUCTION_TYPE_12 = 5'd12,
    INSTRUCTION_TYPE_13 = 5'd13,
    INSTRUCTION_TYPE_14 = 5'd14,
    INSTRUCTION_TYPE_15 = 5'd15,
    INSTRUCTION_TYPE_16 = 5'd16,
    INSTRUCTION_TYPE_17 = 5'd17,
    INSTRUCTION_TYPE_18 = 5'd18,
    INSTRUCTION_TYPE_19 = 5'd19,
    INSTRUCTION_TYPE_20 = 5'd20,
    INSTRUCTION_TYPE_21 = 5'd21,
    INSTRUCTION_TYPE_22 = 5'd22,
    INSTRUCTION_TYPE_23 = 5'd23,
    INSTRUCTION_TYPE_24 = 5'd24,
    INSTRUCTION_TYPE_25 = 5'd25,
    INSTRUCTION_TYPE_26 = 5'd26,
    INSTRUCTION_TYPE_27 = 5'd27,
    INSTRUCTION_TYPE_28 = 5'd28,
    INSTRUCTION_TYPE_29 = 5'd29,
    INSTRUCTION_TYPE_30 = 5'd30
  } instruction_class_t;

  function automatic instruction_class_t decode_instruction_class(
    input program_word_t opcode
  );
    if ((opcode & 24'hc00000) == 24'hc00000) begin
      return INSTRUCTION_TYPE_01;
    end
    else if ((opcode & 24'he00000) == 24'ha00000) begin
      return INSTRUCTION_TYPE_02;
    end
    else if ((opcode & 24'he00000) == 24'h800000) begin
      return INSTRUCTION_TYPE_03;
    end
    else if ((opcode & 24'he00000) == 24'h600000) begin
      return INSTRUCTION_TYPE_04;
    end
    else if ((opcode & 24'hf00000) == 24'h500000) begin
      return INSTRUCTION_TYPE_05;
    end
    else if ((opcode & 24'hf00000) == 24'h400000) begin
      return INSTRUCTION_TYPE_06;
    end
    else if ((opcode & 24'hf00000) == 24'h300000) begin
      return INSTRUCTION_TYPE_07;
    end
    else if ((opcode & 24'hf80000) == 24'h280000) begin
      return INSTRUCTION_TYPE_08;
    end
    else if ((opcode & 24'hf800f0) == 24'h200000) begin
      return INSTRUCTION_TYPE_09;
    end
    else if ((opcode & 24'hf80000) == 24'h180000) begin
      return INSTRUCTION_TYPE_10;
    end
    else if ((opcode & 24'hfc0000) == 24'h140000) begin
      return INSTRUCTION_TYPE_11;
    end
    else if ((opcode & 24'hfe0000) == 24'h120000) begin
      return INSTRUCTION_TYPE_12;
    end
    else if ((opcode & 24'hff0000) == 24'h110000) begin
      return INSTRUCTION_TYPE_13;
    end
    else if ((opcode & 24'hff0000) == 24'h100000) begin
      return INSTRUCTION_TYPE_14;
    end
    else if ((opcode & 24'hff8000) == 24'h0f0000) begin
      return INSTRUCTION_TYPE_15;
    end
    else if ((opcode & 24'hff80f0) == 24'h0e0000) begin
      return INSTRUCTION_TYPE_16;
    end
    else if ((opcode & 24'hfff000) == 24'h0d0000) begin
      return INSTRUCTION_TYPE_17;
    end
    else if ((opcode & 24'hfff00f) == 24'h0c0000) begin
      return INSTRUCTION_TYPE_18;
    end
    else if ((opcode & 24'hffff20) == 24'h0b0000) begin
      return INSTRUCTION_TYPE_19;
    end
    else if ((opcode & 24'hffffe0) == 24'h0a0000) begin
      return INSTRUCTION_TYPE_20;
    end
    else if ((opcode & 24'hffffe0) == 24'h090000) begin
      return INSTRUCTION_TYPE_21;
    end
    else if ((opcode & 24'hfffff0) == 24'h080000) begin
      return INSTRUCTION_TYPE_22;
    end
    else if ((opcode & 24'hfff8ff) == 24'h071000) begin
      return INSTRUCTION_TYPE_23;
    end
    else if ((opcode & 24'hffe0ff) == 24'h060000) begin
      return INSTRUCTION_TYPE_24;
    end
    else if ((opcode & 24'hffffff) == 24'h050000) begin
      return INSTRUCTION_TYPE_25;
    end
    else if ((opcode & 24'hfffff0) == 24'h040000) begin
      return INSTRUCTION_TYPE_26;
    end
    else if ((opcode & 24'hff0000) == 24'h030000) begin
      return INSTRUCTION_TYPE_27;
    end
    else if ((opcode & 24'hff0000) == 24'h020000) begin
      return INSTRUCTION_TYPE_28;
    end
    else if ((opcode & 24'hff0000) == 24'h010000) begin
      return INSTRUCTION_TYPE_29;
    end
    else if ((opcode & 24'hffffff) == 24'h000000) begin
      return INSTRUCTION_TYPE_30;
    end
    else begin
      return INSTRUCTION_RESERVED_UNSHOWN;
    end
  endfunction
endpackage

`default_nettype wire
