`default_nettype none

// Generated by tools/generators/generate_register_package.py.
// Values are the original Appendix A computational DREG field.
package adsp2100_register_pkg;
  typedef enum logic [3:0] {
    DREG_AX0 = 4'h0,
    DREG_AX1 = 4'h1,
    DREG_MX0 = 4'h2,
    DREG_MX1 = 4'h3,
    DREG_AY0 = 4'h4,
    DREG_AY1 = 4'h5,
    DREG_MY0 = 4'h6,
    DREG_MY1 = 4'h7,
    DREG_SI = 4'h8,
    DREG_SE = 4'h9,
    DREG_AR = 4'ha,
    DREG_MR0 = 4'hb,
    DREG_MR1 = 4'hc,
    DREG_MR2 = 4'hd,
    DREG_SR0 = 4'he,
    DREG_SR1 = 4'hf
  } dreg_address_t;
endpackage

`default_nettype wire
