`default_nettype none

// Generated by tools/generators/generate_instruction_formats.py.
// These constants describe original Appendix A bit placement only.
package adsp2100_format_pkg;
  import adsp2100_pkg::*;

  // Original instruction Type 1.
  localparam program_word_t TYPE_01_PD_MASK = 24'h300000;
  localparam logic [4:0] TYPE_01_PD_LSB = 5'd20;
  localparam program_word_t TYPE_01_DD_MASK = 24'h0c0000;
  localparam logic [4:0] TYPE_01_DD_LSB = 5'd18;
  localparam program_word_t TYPE_01_AMF_MASK = 24'h03e000;
  localparam logic [4:0] TYPE_01_AMF_LSB = 5'd13;
  localparam program_word_t TYPE_01_YOP_MASK = 24'h001800;
  localparam logic [4:0] TYPE_01_YOP_LSB = 5'd11;
  localparam program_word_t TYPE_01_XOP_MASK = 24'h000700;
  localparam logic [4:0] TYPE_01_XOP_LSB = 5'd8;
  localparam program_word_t TYPE_01_PM_I_MASK = 24'h0000c0;
  localparam logic [4:0] TYPE_01_PM_I_LSB = 5'd6;
  localparam program_word_t TYPE_01_PM_M_MASK = 24'h000030;
  localparam logic [4:0] TYPE_01_PM_M_LSB = 5'd4;
  localparam program_word_t TYPE_01_DM_I_MASK = 24'h00000c;
  localparam logic [4:0] TYPE_01_DM_I_LSB = 5'd2;
  localparam program_word_t TYPE_01_DM_M_MASK = 24'h000003;
  localparam logic [4:0] TYPE_01_DM_M_LSB = 5'd0;

  // Original instruction Type 2.
  localparam program_word_t TYPE_02_G_MASK = 24'h100000;
  localparam logic [4:0] TYPE_02_G_LSB = 5'd20;
  localparam program_word_t TYPE_02_DATA_MASK = 24'h0ffff0;
  localparam logic [4:0] TYPE_02_DATA_LSB = 5'd4;
  localparam program_word_t TYPE_02_I_MASK = 24'h00000c;
  localparam logic [4:0] TYPE_02_I_LSB = 5'd2;
  localparam program_word_t TYPE_02_M_MASK = 24'h000003;
  localparam logic [4:0] TYPE_02_M_LSB = 5'd0;

  // Original instruction Type 3.
  localparam program_word_t TYPE_03_D_MASK = 24'h100000;
  localparam logic [4:0] TYPE_03_D_LSB = 5'd20;
  localparam program_word_t TYPE_03_RGP_MASK = 24'h0c0000;
  localparam logic [4:0] TYPE_03_RGP_LSB = 5'd18;
  localparam program_word_t TYPE_03_ADDR_MASK = 24'h03fff0;
  localparam logic [4:0] TYPE_03_ADDR_LSB = 5'd4;
  localparam program_word_t TYPE_03_REG_MASK = 24'h00000f;
  localparam logic [4:0] TYPE_03_REG_LSB = 5'd0;

  // Original instruction Type 4.
  localparam program_word_t TYPE_04_G_MASK = 24'h100000;
  localparam logic [4:0] TYPE_04_G_LSB = 5'd20;
  localparam program_word_t TYPE_04_D_MASK = 24'h080000;
  localparam logic [4:0] TYPE_04_D_LSB = 5'd19;
  localparam program_word_t TYPE_04_Z_MASK = 24'h040000;
  localparam logic [4:0] TYPE_04_Z_LSB = 5'd18;
  localparam program_word_t TYPE_04_AMF_MASK = 24'h03e000;
  localparam logic [4:0] TYPE_04_AMF_LSB = 5'd13;
  localparam program_word_t TYPE_04_YOP_MASK = 24'h001800;
  localparam logic [4:0] TYPE_04_YOP_LSB = 5'd11;
  localparam program_word_t TYPE_04_XOP_MASK = 24'h000700;
  localparam logic [4:0] TYPE_04_XOP_LSB = 5'd8;
  localparam program_word_t TYPE_04_DREG_MASK = 24'h0000f0;
  localparam logic [4:0] TYPE_04_DREG_LSB = 5'd4;
  localparam program_word_t TYPE_04_I_MASK = 24'h00000c;
  localparam logic [4:0] TYPE_04_I_LSB = 5'd2;
  localparam program_word_t TYPE_04_M_MASK = 24'h000003;
  localparam logic [4:0] TYPE_04_M_LSB = 5'd0;

  // Original instruction Type 5.
  localparam program_word_t TYPE_05_D_MASK = 24'h080000;
  localparam logic [4:0] TYPE_05_D_LSB = 5'd19;
  localparam program_word_t TYPE_05_Z_MASK = 24'h040000;
  localparam logic [4:0] TYPE_05_Z_LSB = 5'd18;
  localparam program_word_t TYPE_05_AMF_MASK = 24'h03e000;
  localparam logic [4:0] TYPE_05_AMF_LSB = 5'd13;
  localparam program_word_t TYPE_05_YOP_MASK = 24'h001800;
  localparam logic [4:0] TYPE_05_YOP_LSB = 5'd11;
  localparam program_word_t TYPE_05_XOP_MASK = 24'h000700;
  localparam logic [4:0] TYPE_05_XOP_LSB = 5'd8;
  localparam program_word_t TYPE_05_DREG_MASK = 24'h0000f0;
  localparam logic [4:0] TYPE_05_DREG_LSB = 5'd4;
  localparam program_word_t TYPE_05_I_MASK = 24'h00000c;
  localparam logic [4:0] TYPE_05_I_LSB = 5'd2;
  localparam program_word_t TYPE_05_M_MASK = 24'h000003;
  localparam logic [4:0] TYPE_05_M_LSB = 5'd0;

  // Original instruction Type 6.
  localparam program_word_t TYPE_06_DATA_MASK = 24'h0ffff0;
  localparam logic [4:0] TYPE_06_DATA_LSB = 5'd4;
  localparam program_word_t TYPE_06_DREG_MASK = 24'h00000f;
  localparam logic [4:0] TYPE_06_DREG_LSB = 5'd0;

  // Original instruction Type 7.
  localparam program_word_t TYPE_07_RGP_MASK = 24'h0c0000;
  localparam logic [4:0] TYPE_07_RGP_LSB = 5'd18;
  localparam program_word_t TYPE_07_DATA_MASK = 24'h03fff0;
  localparam logic [4:0] TYPE_07_DATA_LSB = 5'd4;
  localparam program_word_t TYPE_07_REG_MASK = 24'h00000f;
  localparam logic [4:0] TYPE_07_REG_LSB = 5'd0;

  // Original instruction Type 8.
  localparam program_word_t TYPE_08_Z_MASK = 24'h040000;
  localparam logic [4:0] TYPE_08_Z_LSB = 5'd18;
  localparam program_word_t TYPE_08_AMF_MASK = 24'h03e000;
  localparam logic [4:0] TYPE_08_AMF_LSB = 5'd13;
  localparam program_word_t TYPE_08_YOP_MASK = 24'h001800;
  localparam logic [4:0] TYPE_08_YOP_LSB = 5'd11;
  localparam program_word_t TYPE_08_XOP_MASK = 24'h000700;
  localparam logic [4:0] TYPE_08_XOP_LSB = 5'd8;
  localparam program_word_t TYPE_08_DEST_DREG_MASK = 24'h0000f0;
  localparam logic [4:0] TYPE_08_DEST_DREG_LSB = 5'd4;
  localparam program_word_t TYPE_08_SOURCE_DREG_MASK = 24'h00000f;
  localparam logic [4:0] TYPE_08_SOURCE_DREG_LSB = 5'd0;

  // Original instruction Type 9.
  localparam program_word_t TYPE_09_Z_MASK = 24'h040000;
  localparam logic [4:0] TYPE_09_Z_LSB = 5'd18;
  localparam program_word_t TYPE_09_AMF_MASK = 24'h03e000;
  localparam logic [4:0] TYPE_09_AMF_LSB = 5'd13;
  localparam program_word_t TYPE_09_YOP_MASK = 24'h001800;
  localparam logic [4:0] TYPE_09_YOP_LSB = 5'd11;
  localparam program_word_t TYPE_09_XOP_MASK = 24'h000700;
  localparam logic [4:0] TYPE_09_XOP_LSB = 5'd8;
  localparam program_word_t TYPE_09_COND_MASK = 24'h00000f;
  localparam logic [4:0] TYPE_09_COND_LSB = 5'd0;

  // Original instruction Type 10.
  localparam program_word_t TYPE_10_S_MASK = 24'h040000;
  localparam logic [4:0] TYPE_10_S_LSB = 5'd18;
  localparam program_word_t TYPE_10_ADDR_MASK = 24'h03fff0;
  localparam logic [4:0] TYPE_10_ADDR_LSB = 5'd4;
  localparam program_word_t TYPE_10_COND_MASK = 24'h00000f;
  localparam logic [4:0] TYPE_10_COND_LSB = 5'd0;

  // Original instruction Type 11.
  localparam program_word_t TYPE_11_ADDR_MASK = 24'h03fff0;
  localparam logic [4:0] TYPE_11_ADDR_LSB = 5'd4;
  localparam program_word_t TYPE_11_TERM_MASK = 24'h00000f;
  localparam logic [4:0] TYPE_11_TERM_LSB = 5'd0;

  // Original instruction Type 12.
  localparam program_word_t TYPE_12_G_MASK = 24'h010000;
  localparam logic [4:0] TYPE_12_G_LSB = 5'd16;
  localparam program_word_t TYPE_12_D_MASK = 24'h008000;
  localparam logic [4:0] TYPE_12_D_LSB = 5'd15;
  localparam program_word_t TYPE_12_SF_MASK = 24'h007800;
  localparam logic [4:0] TYPE_12_SF_LSB = 5'd11;
  localparam program_word_t TYPE_12_XOP_MASK = 24'h000700;
  localparam logic [4:0] TYPE_12_XOP_LSB = 5'd8;
  localparam program_word_t TYPE_12_DREG_MASK = 24'h0000f0;
  localparam logic [4:0] TYPE_12_DREG_LSB = 5'd4;
  localparam program_word_t TYPE_12_I_MASK = 24'h00000c;
  localparam logic [4:0] TYPE_12_I_LSB = 5'd2;
  localparam program_word_t TYPE_12_M_MASK = 24'h000003;
  localparam logic [4:0] TYPE_12_M_LSB = 5'd0;

  // Original instruction Type 13.
  localparam program_word_t TYPE_13_D_MASK = 24'h008000;
  localparam logic [4:0] TYPE_13_D_LSB = 5'd15;
  localparam program_word_t TYPE_13_SF_MASK = 24'h007800;
  localparam logic [4:0] TYPE_13_SF_LSB = 5'd11;
  localparam program_word_t TYPE_13_XOP_MASK = 24'h000700;
  localparam logic [4:0] TYPE_13_XOP_LSB = 5'd8;
  localparam program_word_t TYPE_13_DREG_MASK = 24'h0000f0;
  localparam logic [4:0] TYPE_13_DREG_LSB = 5'd4;
  localparam program_word_t TYPE_13_I_MASK = 24'h00000c;
  localparam logic [4:0] TYPE_13_I_LSB = 5'd2;
  localparam program_word_t TYPE_13_M_MASK = 24'h000003;
  localparam logic [4:0] TYPE_13_M_LSB = 5'd0;

  // Original instruction Type 14.
  localparam program_word_t TYPE_14_UNUSED_X_MASK = 24'h008000;
  localparam logic [4:0] TYPE_14_UNUSED_X_LSB = 5'd15;
  localparam program_word_t TYPE_14_SF_MASK = 24'h007800;
  localparam logic [4:0] TYPE_14_SF_LSB = 5'd11;
  localparam program_word_t TYPE_14_XOP_MASK = 24'h000700;
  localparam logic [4:0] TYPE_14_XOP_LSB = 5'd8;
  localparam program_word_t TYPE_14_DEST_DREG_MASK = 24'h0000f0;
  localparam logic [4:0] TYPE_14_DEST_DREG_LSB = 5'd4;
  localparam program_word_t TYPE_14_SOURCE_DREG_MASK = 24'h00000f;
  localparam logic [4:0] TYPE_14_SOURCE_DREG_LSB = 5'd0;

  // Original instruction Type 15.
  localparam program_word_t TYPE_15_SF_MASK = 24'h007800;
  localparam logic [4:0] TYPE_15_SF_LSB = 5'd11;
  localparam program_word_t TYPE_15_XOP_MASK = 24'h000700;
  localparam logic [4:0] TYPE_15_XOP_LSB = 5'd8;
  localparam program_word_t TYPE_15_EXPONENT_MASK = 24'h0000ff;
  localparam logic [4:0] TYPE_15_EXPONENT_LSB = 5'd0;

  // Original instruction Type 16.
  localparam program_word_t TYPE_16_SF_MASK = 24'h007800;
  localparam logic [4:0] TYPE_16_SF_LSB = 5'd11;
  localparam program_word_t TYPE_16_XOP_MASK = 24'h000700;
  localparam logic [4:0] TYPE_16_XOP_LSB = 5'd8;
  localparam program_word_t TYPE_16_COND_MASK = 24'h00000f;
  localparam logic [4:0] TYPE_16_COND_LSB = 5'd0;

  // Original instruction Type 17.
  localparam program_word_t TYPE_17_DEST_RGP_MASK = 24'h000c00;
  localparam logic [4:0] TYPE_17_DEST_RGP_LSB = 5'd10;
  localparam program_word_t TYPE_17_SOURCE_RGP_MASK = 24'h000300;
  localparam logic [4:0] TYPE_17_SOURCE_RGP_LSB = 5'd8;
  localparam program_word_t TYPE_17_DEST_REG_MASK = 24'h0000f0;
  localparam logic [4:0] TYPE_17_DEST_REG_LSB = 5'd4;
  localparam program_word_t TYPE_17_SOURCE_REG_MASK = 24'h00000f;
  localparam logic [4:0] TYPE_17_SOURCE_REG_LSB = 5'd0;

  // Original instruction Type 18.
  localparam program_word_t TYPE_18_AS_MCC_MASK = 24'h000c00;
  localparam logic [4:0] TYPE_18_AS_MCC_LSB = 5'd10;
  localparam program_word_t TYPE_18_OL_MCC_MASK = 24'h000300;
  localparam logic [4:0] TYPE_18_OL_MCC_LSB = 5'd8;
  localparam program_word_t TYPE_18_BR_MCC_MASK = 24'h0000c0;
  localparam logic [4:0] TYPE_18_BR_MCC_LSB = 5'd6;
  localparam program_word_t TYPE_18_SR_MCC_MASK = 24'h000030;
  localparam logic [4:0] TYPE_18_SR_MCC_LSB = 5'd4;

  // Original instruction Type 19.
  localparam program_word_t TYPE_19_I_MASK = 24'h0000c0;
  localparam logic [4:0] TYPE_19_I_LSB = 5'd6;
  localparam program_word_t TYPE_19_S_MASK = 24'h000010;
  localparam logic [4:0] TYPE_19_S_LSB = 5'd4;
  localparam program_word_t TYPE_19_COND_MASK = 24'h00000f;
  localparam logic [4:0] TYPE_19_COND_LSB = 5'd0;

  // Original instruction Type 20.
  localparam program_word_t TYPE_20_T_MASK = 24'h000010;
  localparam logic [4:0] TYPE_20_T_LSB = 5'd4;
  localparam program_word_t TYPE_20_COND_MASK = 24'h00000f;
  localparam logic [4:0] TYPE_20_COND_LSB = 5'd0;

  // Original instruction Type 21.
  localparam program_word_t TYPE_21_G_MASK = 24'h000010;
  localparam logic [4:0] TYPE_21_G_LSB = 5'd4;
  localparam program_word_t TYPE_21_I_MASK = 24'h00000c;
  localparam logic [4:0] TYPE_21_I_LSB = 5'd2;
  localparam program_word_t TYPE_21_M_MASK = 24'h000003;
  localparam logic [4:0] TYPE_21_M_LSB = 5'd0;

  // Original instruction Type 22.
  localparam program_word_t TYPE_22_COND_MASK = 24'h00000f;
  localparam logic [4:0] TYPE_22_COND_LSB = 5'd0;

  // Original instruction Type 23.
  localparam program_word_t TYPE_23_XOP_MASK = 24'h000700;
  localparam logic [4:0] TYPE_23_XOP_LSB = 5'd8;

  // Original instruction Type 24.
  localparam program_word_t TYPE_24_YOP_MASK = 24'h001800;
  localparam logic [4:0] TYPE_24_YOP_LSB = 5'd11;
  localparam program_word_t TYPE_24_XOP_MASK = 24'h000700;
  localparam logic [4:0] TYPE_24_XOP_LSB = 5'd8;

  // Original instruction Type 26.
  localparam program_word_t TYPE_26_PP_MASK = 24'h000010;
  localparam logic [4:0] TYPE_26_PP_LSB = 5'd4;
  localparam program_word_t TYPE_26_LP_MASK = 24'h000008;
  localparam logic [4:0] TYPE_26_LP_LSB = 5'd3;
  localparam program_word_t TYPE_26_CP_MASK = 24'h000004;
  localparam logic [4:0] TYPE_26_CP_LSB = 5'd2;
  localparam program_word_t TYPE_26_SPP_MASK = 24'h000003;
  localparam logic [4:0] TYPE_26_SPP_LSB = 5'd0;

  // Original instruction Type 27.
  localparam program_word_t TYPE_27_RESERVED_PAYLOAD_MASK = 24'h00ffff;
  localparam logic [4:0] TYPE_27_RESERVED_PAYLOAD_LSB = 5'd0;

  // Original instruction Type 28.
  localparam program_word_t TYPE_28_RESERVED_PAYLOAD_MASK = 24'h00ffff;
  localparam logic [4:0] TYPE_28_RESERVED_PAYLOAD_LSB = 5'd0;

  // Original instruction Type 29.
  localparam program_word_t TYPE_29_RESERVED_PAYLOAD_MASK = 24'h00ffff;
  localparam logic [4:0] TYPE_29_RESERVED_PAYLOAD_LSB = 5'd0;

endpackage

`default_nettype wire
